name: example
description: Web app to test dart-services v2 API.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  codemirror: ^0.6.1
  http: ^0.13.0

dev_dependencies:
  build_runner: ^1.12.2
  build_web_compilers: ^2.16.5
  pedantic: ^1.11.0
