name: example
description: Web app to test dart-services v2 API.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  codemirror: ^0.5.14
  http: ^0.12.0

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
