name: example
description: Web app to test dart-services v2 API.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  codemirror: ^0.7.7
  http: ^0.13.0

dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^3.2.5
  lints: ^2.0.0
