name: example
description: Web app to test dart-services v2 API.
version: 1.0.0

environment:
  sdk: ^2.8.1

dependencies:
  codemirror: ^0.6.2+5.61.1
  http: ^0.13.0

dev_dependencies:
  build_runner: ^2.0.4
  build_web_compilers: ^3.0.0
  pedantic: ^1.9.0
