language: dart
install:
  - gem install coveralls-lcov
dart:
  # Keep this value aligned with min SDK value in pubspec.yaml and FROM line of Dockerfile
  - "2.8.1"
  - beta

# Use Ubuntu 18.04 (Bionic Beaver) 
# https://docs.travis-ci.com/user/reference/overview/#virtualization-environments
dist: bionic
os: linux

branches:
  only: [master, dart-29]
before_script:
  - git submodule init
  - git submodule update
  - export PATH=$PATH:$PWD/flutter/bin
  - flutter doctor
  - flutter config --enable-web
  - flutter precache --web --no-android --no-ios --no-linux --no-windows --no-macos --no-fuchsia
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip
  - unzip protoc-3.11.4-linux-x86_64.zip -d protoc
  - export PATH=$PATH:$PWD/protoc/bin
  - pub global activate protoc_plugin
  - export PATH=$PATH:$HOME/.pub-cache/bin
script: ./tool/travis.sh
