language: dart
install:
  - gem install coveralls-lcov
dart:
  # Keep this value aligned with min SDK value in pubspec.yaml and FROM line of Dockerfile
  - "2.5.2"
  - dev
branches:
  only: [master]
script: ./tool/travis.sh
