language: dart
install:
  - gem install coveralls-lcov
dart:
  - "2.3.0"
  # TODO(devoncarew): commented out due to
  # https://github.com/dart-lang/dart-pad/issues/1002
  #- dev
branches:
  only: [master]
script: ./tool/travis.sh
