language: dart
install:
  - gem install coveralls-lcov
dart:
  # Keep this value aligned with min SDK value in pubspec.yaml and FROM line of Dockerfile
  - "2.8.1"
  - beta

# Use Ubuntu 18.04 (Bionic Beaver) 
# https://docs.travis-ci.com/user/reference/overview/#virtualization-environments
dist: bionic

branches:
  only: [master]
before_script:
  - sudo apt-get update
  - sudo apt-get -y install protobuf-compiler
  - git submodule init
  - git submodule update
  - export PATH=$PATH:$PWD/flutter/bin
  - flutter doctor
  - flutter config --enable-web
  - flutter precache --web --no-android --no-ios --no-linux --no-windows --no-macos --no-fuchsia
  - pub global activate protoc_plugin
  - export PATH=$PATH:$HOME/.pub-cache/bin
script: ./tool/travis.sh
