language: dart
install:
  - gem install coveralls-lcov
dart:
  # Keep this value aligned with min SDK value in pubspec.yaml and FROM line of Dockerfile
  - "2.5.0"
  # TODO(devoncarew): commented out due to
  # https://github.com/dart-lang/dart-pad/issues/1002
  #- dev
branches:
  only: [master]
before_script:
  - git clone https://github.com/flutter/flutter.git -b dev
  - ./flutter/bin/flutter doctor
script: ./tool/travis.sh
