include: package:lints/recommended.yaml

analyzer:
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
  exclude:
    - dart-sdk/**
    - doc/generated/**
    - flutter-sdks/**
    - project_templates/**
    # TODO(https://github.com/dart-lang/dart-pad/issues/1712): This seems to be
    # hiding ~2 dozen legitimate analysis issues.
    - lib/src/protos/**

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - directives_ordering
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_relative_imports
    - prefer_single_quotes
    - sort_pub_dependencies
    - unawaited_futures
