include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - doc/generated/**
    - flutter-sdks/**
    # TODO(https://github.com/dart-lang/dart-pad/issues/1712): This seems to be
    # hiding ~2 dozen legitimate analysis issues.
    - lib/src/protos/**
    - local_pub_cache/**
    - project_templates/**

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - dangling_library_doc_comments
    - directives_ordering
    - library_annotations
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_relative_imports
    - prefer_single_quotes
    - sort_pub_dependencies
    - unawaited_futures
    - unnecessary_library_directive
