include: package:lints/recommended.yaml

analyzer:
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
  exclude:
    - dart-sdk/**
    - doc/generated/**
    - flutter-sdk/**
    - project_templates/null-safe/dart_project/**
    - project_templates/null-unsafe/dart_project/**
    # TODO: This seems to be hiding ~2 dozen legitimate analysis issues. https://github.com/dart-lang/dart-pad/issues/1712
    - lib/src/protos/**

linter:
  rules:
    - always_declare_return_types
    - directives_ordering
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_relative_imports
    - prefer_single_quotes
    - sort_pub_dependencies
    - unawaited_futures
