# Dart analyzer dislikes this line. https://github.com/dart-lang/dart-pad/issues/1720
# include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
  exclude:
    - dart-sdk/**
    - flutter-sdk/**
    - doc/generated/**
    - flutter/**
    # TODO: This seems to be hiding ~2 dozen legitimate analysis issues. https://github.com/dart-lang/dart-pad/issues/1712
    - lib/src/protos/**

linter:
  rules:
    - await_only_futures
    - directives_ordering
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_relative_imports
    - sort_pub_dependencies
