include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  exclude:
    - dart-sdk/**
    - doc/generated/**
    - flutter/**
    # TODO: This seems to be hiding ~2 dozen legitimate analysis issues.
    - lib/src/protos/**

linter:
  rules:
    - directives_ordering
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_relative_imports
    - sort_pub_dependencies
