name: dart_services
publish_to: none

environment:
  # Lock to 2.10.x as this code base is not yet migrated to null safe.
  sdk: ^2.10.4

dependencies:
  analysis_server_lib: ^0.2.0
  analyzer: ^1.2.0
  args: ^2.0.0
  bazel_worker: ^1.0.0
  crypto: ^3.0.1
  # TODO(domesticmouse): Go back to mainline once
  # https://github.com/jcmellado/dartis/pull/38 has landed
  dartis:
    git:
      url: https://github.com/domesticmouse/dartis
      ref: Update-to-lints-and-Dart-2.10
  http: ^0.13.3
  logging: ^1.0.0
  meta: ^1.1.8
  path: ^1.6.2
  protobuf: ^2.0.0
  quiver: ^3.0.1
  shelf: ^1.0.0
  shelf_router: ^1.0.0
  yaml: ^3.0.0

dev_dependencies:
  async: ^2.2.0
  build_runner: ^2.0.4
  coverage: ^1.0.3
  grinder: ^0.9.0
  lints: ^1.0.1
  mock_request: ^1.0.7
  pedantic: ^1.11.0
  shelf_router_generator: ^1.0.0
  synchronized: ^3.0.0
  test: ^1.6.4

executables:
  services: null
