name: dart_services
publish_to: none

environment:
  sdk: ^2.17.0

dependencies:
  analysis_server_lib: ^0.2.0
  analyzer: ^3.2.0
  args: ^2.0.0
  bazel_worker: ^1.0.0
  convert: ^3.0.2
  crypto: ^3.0.2
  encrypt: ^5.0.1
  http: ^0.13.3
  logging: ^1.0.0
  meta: ^1.8.0
  path: ^1.8.2
  protobuf: ^2.1.0
  quiver: ^3.1.0
  resp_client: ^1.2.0
  shelf: ^1.3.1
  shelf_router: ^1.1.3
  yaml: ^3.1.1

dev_dependencies:
  angel3_mock_request: ^6.0.0
  async: ^2.9.0
  build_runner: ^2.1.11
  coverage: ^1.3.2
  grinder: ^0.9.1
  lints: ^2.0.0
  package_config: ^2.1.0
  shelf_router_generator: ^1.0.3
  synchronized: ^3.0.0
  test: ^1.21.3
  test_descriptor: ^2.0.0

executables:
  services: null
