name: dart_services
publish_to: none

environment:
  # Keep SDK aligned with .travis.yml and FROM line of Dockerfile
  sdk: ^2.8.0-dev.20.0

dependencies:
  _discoveryapis_commons: 0.1.9
  analyzer: ^0.39.0
  analysis_server_lib: ^0.1.4
  appengine: ^0.10.3
  args: ^1.5.2
  bazel_worker: ^0.1.23
  crypto: ^2.0.0
  dartis: ^0.4.0
  http: ^0.12.0
  logging: ^0.11.0
  meta: ^1.1.8
  path: ^1.6.2
  protobuf: ^1.0.1
  quiver: ^2.0.3
  rpc: ^0.6.2
  shelf: ^0.7.5
  shelf_router: ^0.7.0+1
  uuid: ^2.0.0
  yaml: ^2.1.15

dev_dependencies:
  async: ^2.2.0
  build_runner: ^1.3.1
  codemirror: ^0.5.6
  coverage: ^0.13.0
  discoveryapis_generator: ^0.9.11
  grinder: ^0.8.0
  # TODO(brettmorgan): return to mock_request pub package after it is
  # published with https://github.com/thosakwe/mock_request/pull/3
  # mock_request: ^1.0.6
  mock_request:
    git: https://github.com/domesticmouse/mock_request.git
  pedantic: ^1.9.0
  shelf_router_generator: ^0.7.0+1
  synchronized: ^2.1.0
  test: ^1.6.4
  tuneup: ^0.3.6

executables:
  services: null
