name: example
description: Web app to test dart-services v2 API.
version: 1.0.0

environment:
  sdk: ^2.8.1

dependencies:
  codemirror: ^0.5.15
  http: ^0.12.0

dev_dependencies:
  build_runner: ^1.8.1
  build_web_compilers: ^2.10.0
  pedantic: ^1.9.0
