name: dart-database
version: 0.1.0
author: Dart Team <misc@dartlang.org>
dependencies:
  appengine: '>=0.3.0 <0.4.0'
  archive: '>=1.0.19 <1.1.0'
  args: '>=0.12.0 <0.14.0'
  crypto: '>=0.9.0 <0.10.0'
  librato: '>=0.0.1 <0.1.0'
  logging: '>=0.9.0 <0.12.0'
  path: ^1.3.0
  shelf: ^0.6.0
  shelf_cors: ^0.2.0
  shelf_route: ^0.12.0
  rpc: ^0.5.0
  yaml: ^2.0.0
  
dev_dependencies:
  grinder: '>=0.7.0 <0.8.0'