name: dart_services_proxy
description: A web server built using the shelf package.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  args: ^1.6.0
  http: ^0.12.1
  meta: ^1.2.2
  protobuf: ^1.0.1
  shelf: ^0.7.7
  shelf_router: ^0.7.2
  uri: ^0.11.3

dev_dependencies:
  build_runner: ^1.10.0
  grinder: ^0.8.0
  pedantic: ^1.9.0
  shelf_router_generator: ^0.7.0+1
