name: dart_compiler
description: The Dart compiler endpoint for DartPad

environment:
  sdk: '>=2.5.2 <3.0.0'

dependencies:
  dart_services:
    path: ../dart_services

dev_dependencies:
  coverage: ^0.13.0
  grinder: ^0.8.0
  pedantic: ^1.8.0
  test: ^1.6.4
