name: flutter_web_test
publish_to: none

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter_web: any
  collection: ^1.0.0
  html: '>=0.13.3 <0.15.0'
  intl: ^0.15.7
  meta: ^1.1.5
  quiver: ^2.0.1
  vector_math: ^2.0.7
  test: ^1.3.0

dependency_overrides:
  flutter_web:
    path: ../flutter_web
  flutter_web_ui:
    path: ../flutter_web_ui
