name: flutter_web_ui
publish_to: none

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  collection: ^1.0.0
  meta: ^1.1.5
  vector_math: ^2.0.7
  intl: any

dev_dependencies:
  path: any
  quiver: ^2.0.4
  test: ^1.3.0
