include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  exclude:
    - 'dart-sdk/**'
    - 'third_party/**'
    - 'doc/generated/**'
    - 'flutter_web/**'
