name: dart-services

on:
  # Run CI on pushes to the master branch, and on PRs against master.
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
      
defaults:
  run:
    shell: bash

jobs:
  analyze:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable,beta,dev]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v0.1
        with:
          channel: ${{ matrix.sdk }}
      - name: Install dependencies
        run: sudo apt-get install -y protobuf-compiler redis
      - name: Install dependencies
        run: dart pub get
      - name: Analyze code (example/)
        run: |
          cd example
          echo [Analyzing example]
          dart pub get
          dart analyze --fatal-infos .
      - name: Analyze code
        run: dart analyze --fatal-infos .
      - name: Prepare Flutter
        run: |
          git submodule init
          git submodule update
          export PATH=$PATH:$PWD/flutter/bin
          flutter doctor -v
          flutter config --enable-web
      - name: Run tests
        run: |
          export PATH=$PATH:$HOME/.pub-cache/bin
          dart pub global activate protoc_plugin
          ./tool/travis.sh
